[package]
name = "compatforge-process"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
compatforge-domain = { path = "../compatforge-domain" }
compatforge-guest-artifact = { path = "../compatforge-guest-artifact" }
sha2.workspace = true

[dev-dependencies]
serde_json.workspace = true

[lints]
workspace = true
